Repository KUIT-AGARANG/Agarang-Backend, pull requests merged in 2024-09, with the labels that each got.

#122 [Feat] SSE 알림 서비스 구현
  src/main/java/com/kuit/agarang/domain/ai/service/MusicGenService.java
  src/main/java/com/kuit/agarang/domain/notification/controller/SseController.java
  src/main/java/com/kuit/agarang/domain/notification/service/SseService.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
Labels: ✨ Feature

#121 fix: tts get방식 & historyMessage 저장 방식
  .github/workflows/CICD.yml
  src/main/java/com/kuit/agarang/domain/ai/service/AIService.java
  src/main/java/com/kuit/agarang/domain/ai/utils/GPTUtil.java
Labels: 🐞 BugFix, 🔨 Refactor

#124 [Test] sse notification 테스트용 컨트롤러 구현
  src/main/java/com/kuit/agarang/domain/ai/service/MusicGenService.java
  src/main/java/com/kuit/agarang/domain/notification/controller/TestController.java
  src/main/java/com/kuit/agarang/domain/notification/service/SseService.java
Labels: 🌏 Deploy, 🐞 BugFix
