Repository KUIT-AGARANG/Agarang-Backend, pull requests merged in 2024-08, with the labels that each got.

#72 [Feature] 음악 선택사항 저장 및 ai & file 예외 처리
  src/main/java/com/kuit/agarang/domain/ai/controller/MemoryAIController.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/MusicAnswer.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/MusicInfo.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/TextAnswer.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/gpt/GPTImageDescription.java
  src/main/java/com/kuit/agarang/domain/ai/model/entity/cache/GPTChatHistory.java
  src/main/java/com/kuit/agarang/domain/ai/service/MemoryAIService.java
  src/main/java/com/kuit/agarang/domain/ai/service/TypecastService.java
  src/main/java/com/kuit/agarang/domain/ai/utils/GPTUtil.java
  src/main/java/com/kuit/agarang/global/common/config/SecurityConfig.java
  src/main/java/com/kuit/agarang/global/common/exception/exception/FileException.java
  src/main/java/com/kuit/agarang/global/common/exception/exception/OpenAPIException.java
  src/main/java/com/kuit/agarang/global/common/exception/handler/ControllerExceptionHandler.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
  src/main/java/com/kuit/agarang/global/common/service/RedisService.java
  src/main/java/com/kuit/agarang/global/s3/utils/S3FileUtil.java
  src/main/java/com/kuit/agarang/global/s3/utils/S3Util.java
  src/test/java/com/kuit/agarang/global/common/service/RedisServiceTest.java
Labels: 🐞 BugFix, 🔨 Refactor

#75 [Feature] 홈화면 캐릭터 말풍선 생성 (gpt)
  src/main/java/com/kuit/agarang/domain/ai/controller/MemoryAIController.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/gpt/AbstractGPTRequest.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/gpt/GPTContent.java
  src/main/java/com/kuit/agarang/domain/ai/model/enums/GPTPrompt.java
  src/main/java/com/kuit/agarang/domain/ai/model/enums/GPTSystemRole.java
  src/main/java/com/kuit/agarang/domain/ai/service/AIService.java
  src/main/java/com/kuit/agarang/domain/ai/service/GPTChatService.java
  src/main/java/com/kuit/agarang/domain/ai/utils/GPTPromptUtil.java
  src/main/java/com/kuit/agarang/domain/ai/utils/GPTUtil.java
  src/main/java/com/kuit/agarang/global/s3/model/dto/S3File.java
  src/test/java/com/kuit/agarang/domain/ai/model/dto/gpt/GPTDtoTest.java
Labels: 🔨 Refactor, 📬 API, ✨ Feature

#76 [Feature] GPT 를 활용한 musicgen promt 및 노래 제목 생성
  src/main/java/com/kuit/agarang/domain/ai/controller/MemoryAIController.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/MusicInfo.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/gpt/GPTImageDescription.java
  src/main/java/com/kuit/agarang/domain/ai/model/entity/cache/GPTChatHistory.java
  src/main/java/com/kuit/agarang/domain/ai/model/enums/GPTSystemRole.java
  src/main/java/com/kuit/agarang/domain/ai/service/AIService.java
  src/main/java/com/kuit/agarang/domain/ai/service/GPTChatService.java
  src/main/java/com/kuit/agarang/domain/ai/utils/GPTPromptUtil.java
  src/main/java/com/kuit/agarang/domain/ai/utils/GPTUtil.java
  src/main/java/com/kuit/agarang/global/s3/model/dto/S3File.java
  src/test/java/com/kuit/agarang/global/common/service/RedisServiceTest.java
Labels: 🔨 Refactor, 📬 API, ✨ Feature

#77 [Feature] Baby code 생성 및 로그인 Controller 통합
  build.gradle
  src/main/java/com/kuit/agarang/domain/baby/model/entity/Baby.java
  src/main/java/com/kuit/agarang/domain/baby/repository/BabyRepository.java
  src/main/java/com/kuit/agarang/domain/home/service/CharacterService.java
  src/main/java/com/kuit/agarang/domain/home/service/HomeService.java
  src/main/java/com/kuit/agarang/domain/home/service/SettingService.java
  src/main/java/com/kuit/agarang/domain/login/controller/LoginController.java
  src/main/java/com/kuit/agarang/domain/login/filter/JWTFilter.java
  src/main/java/com/kuit/agarang/domain/login/utils/JWTUtil.java
  src/main/java/com/kuit/agarang/domain/member/model/dto/BabyDueDateRequest.java
  src/main/java/com/kuit/agarang/domain/member/model/dto/BabyNameRequest.java
  src/main/java/com/kuit/agarang/domain/member/model/dto/NewBabyRequest.java
  src/main/java/com/kuit/agarang/domain/member/model/dto/ProcessBabyRequest.java
  src/main/java/com/kuit/agarang/domain/member/model/entity/Member.java
  src/main/java/com/kuit/agarang/domain/member/repository/MemberRepository.java
  src/main/java/com/kuit/agarang/domain/member/service/MemberService.java
  src/main/java/com/kuit/agarang/global/common/exception/handler/ControllerExceptionHandler.java
  src/main/java/com/kuit/agarang/global/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/kuit/agarang/global/common/utils/CodeUtil.java
  src/main/resources/data.sql
  src/test/java/com/kuit/agarang/global/common/utils/CodeUtilTest.java
Labels: 🔨 Refactor, 📬 API, ✨ Feature

#81 [Hotfix] memory 삭제 시 hashtag 삭제 누락
  src/main/java/com/kuit/agarang/domain/memory/repository/HashTagRepository.java
  src/main/java/com/kuit/agarang/domain/memory/service/MemoryService.java
Labels: 🐞 BugFix

#80 [Feature] 노래 즐겨찾기, 삭제 기능 API 구현 및 리팩토링
  src/main/java/com/kuit/agarang/domain/memory/model/entity/MusicBookmark.java
  src/main/java/com/kuit/agarang/domain/memory/repository/MemoryRepository.java
  src/main/java/com/kuit/agarang/domain/memory/repository/MusicBookmarkRepository.java
  src/main/java/com/kuit/agarang/domain/playlist/controller/PlaylistController.java
  src/main/java/com/kuit/agarang/domain/playlist/model/dto/DeleteMusicRequest.java
  src/main/java/com/kuit/agarang/domain/playlist/model/dto/MusicBookmarkRequest.java
  src/main/java/com/kuit/agarang/domain/playlist/model/dto/MusicDto.java
  src/main/java/com/kuit/agarang/domain/playlist/model/dto/PlaylistTracksResponse.java
  src/main/java/com/kuit/agarang/domain/playlist/model/entity/MemoryPlaylist.java
  src/main/java/com/kuit/agarang/domain/playlist/repository/MemoryPlaylistRepository.java
  src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
Labels: 🔨 Refactor, 📬 API, ✨ Feature

#85 Feat : ID값으로 추억 조회 API 추가 및 이미지 URL 추가
  src/main/java/com/kuit/agarang/domain/member/repository/MemberRepository.java
  src/main/java/com/kuit/agarang/domain/memory/controller/MemoryController.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/CardMemoriesResponse.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryDTO.java
  src/main/java/com/kuit/agarang/domain/memory/repository/MemoryBookmarkRepository.java
  src/main/java/com/kuit/agarang/domain/memory/repository/MemoryRepository.java
  src/main/java/com/kuit/agarang/domain/memory/service/MemoryService.java
  src/main/java/com/kuit/agarang/global/common/config/SwaggerConfig.java
  src/main/resources/application-local.yml
  src/main/resources/data.sql
Labels: 📬 API

#88 [Feature] Token Bearer 추가,
  src/main/java/com/kuit/agarang/domain/baby/repository/BabyRepository.java
  src/main/java/com/kuit/agarang/domain/home/controller/CharacterController.java
  src/main/java/com/kuit/agarang/domain/home/controller/HomeController.java
  src/main/java/com/kuit/agarang/domain/home/controller/SettingController.java
  src/main/java/com/kuit/agarang/domain/home/model/dto/HomeResponse.java
  src/main/java/com/kuit/agarang/domain/home/service/CharacterService.java
  src/main/java/com/kuit/agarang/domain/home/service/HomeService.java
  src/main/java/com/kuit/agarang/domain/home/service/SettingService.java
  src/main/java/com/kuit/agarang/domain/login/filter/JWTFilter.java
  src/main/java/com/kuit/agarang/domain/login/service/JWTService.java
  src/main/java/com/kuit/agarang/domain/login/utils/JWTUtil.java
  src/main/java/com/kuit/agarang/domain/member/service/MemberService.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
  src/main/resources/application-local.yml
  src/main/resources/data.sql
Labels: 🐞 BugFix, 📬 API

#84 [Feature] meta musicgen 음악 생성 및 DB 저장 구현
  src/main/java/com/kuit/agarang/domain/ai/controller/MemoryAIController.java
  src/main/java/com/kuit/agarang/domain/ai/controller/MusicGenController.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/MemoryTextInfo.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/gpt/GPTImageDescription.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/musicGen/MusicGenRequest.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/musicGen/MusicGenResponse.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/typecast/TypecastRequest.java
  src/main/java/com/kuit/agarang/domain/ai/model/entity/cache/GPTChatHistory.java
  src/main/java/com/kuit/agarang/domain/ai/service/AIService.java
  src/main/java/com/kuit/agarang/domain/ai/service/MusicGenService.java
  src/main/java/com/kuit/agarang/domain/ai/service/TypecastService.java
  src/main/java/com/kuit/agarang/domain/ai/utils/GPTPromptUtil.java
  src/main/java/com/kuit/agarang/domain/ai/utils/MusicGenClientUtil.java
  src/main/java/com/kuit/agarang/domain/member/repository/MemberRepository.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryDTO.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/Hashtag.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/Memory.java
  src/main/java/com/kuit/agarang/domain/memory/repository/MemoryRepository.java
  src/main/java/com/kuit/agarang/domain/playlist/model/dto/MusicDto.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
  src/main/java/com/kuit/agarang/global/s3/model/dto/S3File.java
  src/main/java/com/kuit/agarang/global/s3/utils/S3FileUtil.java
  src/main/java/com/kuit/agarang/global/s3/utils/S3Util.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/logback.xml
Labels: 🔨 Refactor, 📬 API, ✨ Feature

#89 [Feature] 필터 예외처리 핸들러 구현
  src/main/java/com/kuit/agarang/domain/login/filter/JWTFilter.java
  src/main/java/com/kuit/agarang/global/common/config/SecurityConfig.java
  src/main/java/com/kuit/agarang/global/common/exception/exception/BusinessException.java
  src/main/java/com/kuit/agarang/global/common/exception/handler/FilterExceptionHandler.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
Labels: 🐞 BugFix

#90 [Refactor] JWT 토큰 응답 방식 변경
  src/main/java/com/kuit/agarang/domain/login/controller/ReissueController.java
  src/main/java/com/kuit/agarang/domain/login/filter/JWTFilter.java
  src/main/java/com/kuit/agarang/domain/login/handler/CustomSuccessHandler.java
  src/main/java/com/kuit/agarang/domain/login/service/CustomOAuth2UserService.java
  src/main/java/com/kuit/agarang/domain/login/service/JWTService.java
  src/main/java/com/kuit/agarang/domain/login/utils/JWTUtil.java
  src/main/java/com/kuit/agarang/domain/member/model/dto/MemberDTO.java
  src/main/java/com/kuit/agarang/domain/member/model/entity/Member.java
  src/main/java/com/kuit/agarang/domain/member/model/entity/RefreshToken.java
  src/main/java/com/kuit/agarang/domain/member/repository/MemberRepository.java
  src/main/java/com/kuit/agarang/domain/member/repository/RefreshRepository.java
  src/main/java/com/kuit/agarang/global/common/exception/exception/JWTException.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
Labels: 🔨 Refactor

#91 [Hotfix] 엑세스 토큰 쿠키 추가
  src/main/java/com/kuit/agarang/domain/login/handler/CustomSuccessHandler.java
Labels: 🐞 BugFix

#94 [Fix] AccessToken Cookie 변경 및 Bearer Prefix 제거
  src/main/java/com/kuit/agarang/domain/login/controller/ReissueController.java
  src/main/java/com/kuit/agarang/domain/login/filter/JWTFilter.java
  src/main/java/com/kuit/agarang/domain/login/handler/CustomSuccessHandler.java
  src/main/java/com/kuit/agarang/domain/login/utils/JWTUtil.java
Labels: 🐞 BugFix

#95 [Fix] jwt access 토큰 쿠키화
  src/main/java/com/kuit/agarang/domain/login/controller/ReissueController.java
  src/main/java/com/kuit/agarang/domain/login/filter/JWTFilter.java
  src/main/java/com/kuit/agarang/domain/login/handler/CustomSuccessHandler.java
  src/main/java/com/kuit/agarang/domain/login/utils/JWTUtil.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
Labels: 🐞 BugFix

#96 [HotFix] cookie NPE
  src/main/java/com/kuit/agarang/domain/login/filter/JWTFilter.java
Labels: 🐞 BugFix

#97 Hot fix/webhook permitall
  src/main/java/com/kuit/agarang/domain/login/filter/JWTFilter.java
  src/main/java/com/kuit/agarang/global/common/config/SecurityConfig.java
Labels: ✨ Feature

#101 [HotFix] refresh redis 저장 key-value 수정
  src/main/java/com/kuit/agarang/domain/login/handler/CustomSuccessHandler.java
  src/main/java/com/kuit/agarang/domain/login/service/JWTService.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
Labels: 🐞 BugFix

#93 [Feature] 플레이리스트 구분 저장을 위한 Util 구현
  src/main/java/com/kuit/agarang/domain/ai/service/AIService.java
  src/main/java/com/kuit/agarang/domain/memory/enums/Instrument.java
  src/main/java/com/kuit/agarang/domain/playlist/util/MusicSaveUtil.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
Labels: ✨ Feature

#102 [HotFix] login-success JWTFilter 무시
  src/main/java/com/kuit/agarang/domain/login/filter/JWTFilter.java
  src/main/java/com/kuit/agarang/domain/login/service/JWTService.java
Labels: 🐞 BugFix

#103 [hotFix] 홈 세팅 시 캐릭터 URL 리턴
  src/main/java/com/kuit/agarang/domain/home/model/dto/GlobalSettingResponse.java
  src/main/java/com/kuit/agarang/domain/home/service/SettingService.java
Labels: 🔨 Refactor

#105 [Feat] 캐릭터 레벨 2 이미지 구현
  src/main/java/com/kuit/agarang/domain/baby/model/entity/Character.java
  src/main/java/com/kuit/agarang/domain/baby/repository/CharacterRepository.java
  src/main/java/com/kuit/agarang/domain/home/model/dto/CharacterSettingResponse.java
  src/main/java/com/kuit/agarang/domain/home/model/dto/HomeResponse.java
  src/main/java/com/kuit/agarang/domain/home/service/CharacterService.java
  src/main/java/com/kuit/agarang/domain/home/service/HomeService.java
  src/main/java/com/kuit/agarang/domain/home/service/SettingService.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryImageDTO.java
  src/main/java/com/kuit/agarang/domain/playlist/model/entity/Playlist.java
Labels: 🔨 Refactor

#106 [Fix] home
  src/main/java/com/kuit/agarang/domain/home/service/SettingService.java
  src/main/java/com/kuit/agarang/domain/login/controller/LoginController.java
  src/main/java/com/kuit/agarang/domain/member/service/MemberService.java
Labels: 🔨 Refactor

#108 [Fix] Baby 테이블의 필드 babyCode 네이빙 변경 (code)
  src/main/java/com/kuit/agarang/domain/baby/model/entity/Baby.java
  src/main/java/com/kuit/agarang/domain/home/service/SettingService.java
  src/main/java/com/kuit/agarang/domain/member/service/MemberService.java
Labels: 🔨 Refactor

#109 [Fix] babyCode 빌드 오류
  src/main/java/com/kuit/agarang/domain/baby/repository/BabyRepository.java
  src/main/java/com/kuit/agarang/domain/member/service/MemberService.java
Labels: 🐞 BugFix

#110 [Refactor] memory 관련 dto 반환 시 Id 추가
  src/main/java/com/kuit/agarang/domain/home/service/SettingService.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryDTO.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MonthlyMemoryDTO.java
  src/main/java/com/kuit/agarang/domain/memory/repository/MemoryRepository.java
  src/main/java/com/kuit/agarang/domain/memory/service/MemoryService.java
Labels: 🔨 Refactor

#111 [Fix] 일별 메모리 반환 시 1일부터 반환
  src/main/java/com/kuit/agarang/domain/memory/repository/MemoryRepository.java
Labels: 🔨 Refactor

#112 [Fix] 일별 메모리 반환 시 1일부터 반환
  src/main/java/com/kuit/agarang/domain/memory/repository/MemoryRepository.java
  src/main/java/com/kuit/agarang/domain/memory/service/MemoryService.java
Labels: 🔨 Refactor

#113 [Fix] MonthlyMemoryDTO 수정
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MonthlyMemoryDTO.java
Labels: ✨ Feature

#114 [Fix] MemoryDTO 수정
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryDTO.java
Labels: ✨ Feature

#115 [Fix] 메모리 조회&삭제 검증 및 아이디 수정
  src/main/java/com/kuit/agarang/domain/ai/service/AIService.java
  src/main/java/com/kuit/agarang/domain/memory/controller/MemoryController.java
  src/main/java/com/kuit/agarang/domain/memory/service/MemoryService.java
  src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
Labels: 🐞 BugFix
