Repository KUIT-AGARANG/Agarang-Backend, pull requests merged in 2024-07, with the labels that each got.

#9 JPA 도메인 설계
  src/main/java/com/kuit/agarang/AgarangApplication.java
  src/main/java/com/kuit/agarang/common/model/entity/BaseEntity.java
  src/main/java/com/kuit/agarang/common/model/entity/Status.java
  src/main/java/com/kuit/agarang/domain/baby/model/entity/Baby.java
  src/main/java/com/kuit/agarang/domain/baby/model/entity/Character.java
  src/main/java/com/kuit/agarang/domain/member/model/entity/Member.java
  src/main/java/com/kuit/agarang/domain/member/model/entity/RefreshToken.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/Hashtag.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/Memory.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/MemoryBookmark.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/MusicBookmark.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/enums/Genre.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/enums/Instrument.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/enums/Mood.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/enums/Tempo.java
  src/main/java/com/kuit/agarang/domain/playlist/model/entity/MemoryPlaylist.java
  src/main/java/com/kuit/agarang/domain/playlist/model/entity/Playlist.java
Labels: ✨ Feature

#6 [Feature] Text To Speech (캐릭터 말풍선 오디오 변환)
  build.gradle
  src/main/java/com/kuit/agarang/domain/memory/config/WebClientConfig.java
  src/main/java/com/kuit/agarang/domain/memory/dto/MessageRequest.java
  src/main/java/com/kuit/agarang/domain/memory/dto/TypecastAudioResponse.java
  src/main/java/com/kuit/agarang/domain/memory/dto/TypecastErrorResponse.java
  src/main/java/com/kuit/agarang/domain/memory/dto/TypecastRequest.java
  src/main/java/com/kuit/agarang/domain/memory/dto/TypecastResponse.java
  src/main/java/com/kuit/agarang/domain/memory/service/TypecastService.java
  src/main/java/com/kuit/agarang/domain/memory/utils/TypecastClientUtil.java
  src/main/java/com/kuit/agarang/domain/memory/utils/WebClientUtil.java
  src/main/java/com/kuit/agarang/global/config/SecurityConfig.java
  src/main/java/com/kuit/agarang/global/deploy/controller/HealthCheckController.java
  src/main/java/com/kuit/agarang/global/deploy/dto/ServerInfo.java
Labels: ⚙ Setting, 🔨 Refactor, ✨ Feature

#11 [Docs] 패키지 구조 중간 정리
  src/main/java/com/kuit/agarang/common/model/entity/Status.java
  src/main/java/com/kuit/agarang/domain/ai/config/WebClientConfig.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/MessageRequest.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/TypecastAudioResponse.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/TypecastErrorResponse.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/TypecastRequest.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/TypecastResponse.java
  src/main/java/com/kuit/agarang/domain/ai/service/TypecastService.java
  src/main/java/com/kuit/agarang/domain/ai/utils/TypecastClientUtil.java
  src/main/java/com/kuit/agarang/domain/ai/utils/WebClientUtil.java
  src/main/java/com/kuit/agarang/domain/baby/model/entity/Baby.java
  src/main/java/com/kuit/agarang/domain/baby/model/entity/Character.java
  src/main/java/com/kuit/agarang/domain/member/model/entity/Member.java
  src/main/java/com/kuit/agarang/domain/member/model/entity/RefreshToken.java
  src/main/java/com/kuit/agarang/domain/memory/enums/Genre.java
  src/main/java/com/kuit/agarang/domain/memory/enums/Instrument.java
  src/main/java/com/kuit/agarang/domain/memory/enums/Mood.java
  src/main/java/com/kuit/agarang/domain/memory/enums/Tempo.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/Hashtag.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/Memory.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/MemoryBookmark.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/MusicBookmark.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/enums/Tempo.java
  src/main/java/com/kuit/agarang/domain/playlist/model/entity/MemoryPlaylist.java
  src/main/java/com/kuit/agarang/domain/playlist/model/entity/Playlist.java
  src/main/java/com/kuit/agarang/global/deploy/controller/HealthCheckController.java
  src/main/java/com/kuit/agarang/global/deploy/model/dto/ServerInfo.java
  src/main/java/com/kuit/agarang/global/entity/BaseEntity.java
  src/main/java/com/kuit/agarang/global/entity/Status.java
Labels: 📃 Docs, 🔨 Refactor

#12 [CICD] develop push 시 자동 배포
  .github/workflows/CICD.yml
Labels: 🌏 Deploy

#16 [Docs] 확정된 디렉토리 구조 반영
  src/main/java/com/kuit/agarang/domain/baby/model/entity/Baby.java
  src/main/java/com/kuit/agarang/domain/baby/model/entity/Character.java
  src/main/java/com/kuit/agarang/domain/member/model/entity/Member.java
  src/main/java/com/kuit/agarang/domain/member/model/entity/RefreshToken.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/Hashtag.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/Memory.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/MemoryBookmark.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/MusicBookmark.java
  src/main/java/com/kuit/agarang/domain/playlist/model/entity/MemoryPlaylist.java
  src/main/java/com/kuit/agarang/domain/playlist/model/entity/Playlist.java
  src/main/java/com/kuit/agarang/global/common/config/SecurityConfig.java
  src/main/java/com/kuit/agarang/global/common/model/entity/BaseEntity.java
  src/main/java/com/kuit/agarang/global/common/model/enums/Status.java
  src/main/java/com/kuit/agarang/global/entity/Status.java
Labels: 📃 Docs, 🔨 Refactor

#19 [Feature] AWS S3 단일 파일 업로드
  build.gradle
  src/main/java/com/kuit/agarang/global/s3/config/S3Config.java
  src/main/java/com/kuit/agarang/global/s3/model/enums/FileCategory.java
  src/main/java/com/kuit/agarang/global/s3/utils/S3Util.java
  src/main/resources/application.yml
Labels: 📬 API, ✨ Feature

#20 [Refactor] S3Util -> S3FileUtil & S3Util 로 기능별 분리
  src/main/java/com/kuit/agarang/global/s3/model/dto/S3File.java
  src/main/java/com/kuit/agarang/global/s3/model/enums/ContentType.java
  src/main/java/com/kuit/agarang/global/s3/model/enums/FileCategory.java
  src/main/java/com/kuit/agarang/global/s3/utils/S3FileUtil.java
  src/main/java/com/kuit/agarang/global/s3/utils/S3Util.java
  src/main/resources/application.yml
Labels: 🔨 Refactor, ✨ Feature

#28 [Infra] 서버 환경설정 파일 분리 및 gitignore 처리
  .gitignore
  Dockerfile
  src/main/java/com/kuit/agarang/global/deploy/controller/HealthCheckController.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ⚙ Setting, 🌏 Deploy

#23 [Feature] 다이어리 탭 조회 기능 구현
  src/main/java/com/kuit/agarang/domain/baby/model/entity/Baby.java
  src/main/java/com/kuit/agarang/domain/member/model/entity/Member.java
  src/main/java/com/kuit/agarang/domain/memory/controller/MemoryController.java
  src/main/java/com/kuit/agarang/domain/memory/enums/ViewType.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/DailyMemoriesResponse.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/DailyMemoryDTO.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/DailyMemoryResponse.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/FavoriteMemoriesResponse.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryBookmarkedDTO.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryDTO.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryImageDTO.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryRequest.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MonthlyMemoryDTO.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MonthlyMemoryResponse.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/Memory.java
  src/main/java/com/kuit/agarang/domain/memory/repository/MemoryBookmarkRepository.java
  src/main/java/com/kuit/agarang/domain/memory/repository/MemoryRepository.java
  src/main/java/com/kuit/agarang/domain/memory/service/MemoryService.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponse.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
  src/main/java/com/kuit/agarang/global/common/utils/DateUtil.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/kuit/agarang/domain/memory/repository/MemoryRepositoryTest.java
  src/test/java/com/kuit/agarang/global/common/utils/DateUtilTest.java
Labels: ⚙ Setting, 📬 API, ✨ Feature

#22 [Feature] Kakao login구현, Jwt 토큰 발행
  build.gradle
  src/main/java/com/kuit/agarang/domain/login/enums/AuthProvider.java
  src/main/java/com/kuit/agarang/domain/login/handler/OAuth2SuccessHandler.java
  src/main/java/com/kuit/agarang/domain/login/model/entitiy/CustomOAuth2User.java
  src/main/java/com/kuit/agarang/domain/login/service/LoginService.java
  src/main/java/com/kuit/agarang/domain/login/util/JwtProvider.java
  src/main/java/com/kuit/agarang/domain/member/model/entity/Member.java
  src/main/java/com/kuit/agarang/domain/member/repository/MemberRepository.java
  src/main/java/com/kuit/agarang/global/common/config/SecurityConfig.java
  src/main/java/com/kuit/agarang/global/common/exception/jwt/bad_request/JwtBadRequestException.java
  src/main/java/com/kuit/agarang/global/common/exception/jwt/bad_request/JwtNoTokenException.java
  src/main/java/com/kuit/agarang/global/common/exception/jwt/bad_request/JwtUnsupportedTokenException.java
  src/main/java/com/kuit/agarang/global/common/exception/jwt/unauthorized/JwtExpiredTokenException.java
  src/main/java/com/kuit/agarang/global/common/exception/jwt/unauthorized/JwtInvalidTokenException.java
  src/main/java/com/kuit/agarang/global/common/exception/jwt/unauthorized/JwtMalformedTokenException.java
  src/main/java/com/kuit/agarang/global/common/exception/jwt/unauthorized/JwtUnauthorizedTokenException.java
  src/main/java/com/kuit/agarang/global/common/response/BaseErrorResponse.java
  src/main/java/com/kuit/agarang/global/common/response/BaseResponse.java
  src/main/java/com/kuit/agarang/global/common/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/kuit/agarang/global/common/response/status/ResponseStatus.java
Labels: ⚙ Setting, ✨ Feature

#37 [Infra] Swagger 구축
  build.gradle
  src/main/java/com/kuit/agarang/domain/memory/controller/MemoryController.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryDTO.java
  src/main/java/com/kuit/agarang/global/common/config/SecurityConfig.java
  src/main/java/com/kuit/agarang/global/common/config/SwaggerConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ⚙ Setting, 📃 Docs

#39 [Feat] 서버 에러로그 발생 시 디스코드 알림 연동
  build.gradle
  src/main/java/com/kuit/agarang/global/common/config/ProdWebConfig.java
  src/main/java/com/kuit/agarang/global/discord/interceptor/ProdErrorInterceptor.java
  src/main/java/com/kuit/agarang/global/discord/model/dto/HeaderInfo.java
  src/main/resources/logback.xml
Labels: ⚙ Setting, ✨ Feature

#45 [CICD] PR 생성 시 배포 & 테스트 진행
  .github/workflows/PR-TEST.yml
Labels: ⚙ Setting, 🌏 Deploy

#47 [Feature] TTS 요청 시 webhook 으로 응답 받기
  src/main/java/com/kuit/agarang/domain/ai/controller/TypecastController.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/MessageRequest.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/TypecastWebhookResponse.java
  src/main/java/com/kuit/agarang/domain/ai/model/entity/TypecastAudio.java
  src/main/java/com/kuit/agarang/domain/ai/model/repository/TypecastAudioRepository.java
  src/main/java/com/kuit/agarang/domain/ai/service/TypecastService.java
  src/main/java/com/kuit/agarang/domain/ai/utils/TypecastClientUtil.java
Labels: 📬 API, ✨ Feature

#31 [Setting] CustomException & ExceptionHandler 생성
  src/main/java/com/kuit/agarang/global/common/exception/exception/AgarangException.java
  src/main/java/com/kuit/agarang/global/common/exception/handler/AgarangExceptionHandler.java
Labels: ⚙ Setting, ✨ Feature

#60 [Feature] Redis 캐시 구현 및 ai-service 반영
  build.gradle
  src/main/java/com/kuit/agarang/domain/ai/model/dto/gpt/GPTChat.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/gpt/GPTImageDescription.java
  src/main/java/com/kuit/agarang/domain/ai/model/dto/gpt/GPTRequest.java
  src/main/java/com/kuit/agarang/domain/ai/model/entity/GPTChatHistory.java
  src/main/java/com/kuit/agarang/domain/ai/model/entity/TypecastAudio.java
  src/main/java/com/kuit/agarang/domain/ai/model/entity/cache/GPTChatHistory.java
  src/main/java/com/kuit/agarang/domain/ai/repository/GPTChatHistoryRepository.java
  src/main/java/com/kuit/agarang/domain/ai/repository/TypecastAudioRepository.java
  src/main/java/com/kuit/agarang/domain/ai/service/GPTService.java
  src/main/java/com/kuit/agarang/domain/ai/service/MemoryAIService.java
  src/main/java/com/kuit/agarang/domain/ai/service/TypecastService.java
  src/main/java/com/kuit/agarang/domain/ai/utils/GPTUtil.java
  src/main/java/com/kuit/agarang/global/common/config/RedisConfig.java
  src/main/java/com/kuit/agarang/global/common/controller/HealthCheckController.java
  src/main/java/com/kuit/agarang/global/common/service/RedisService.java
  src/main/java/com/kuit/agarang/global/deploy/model/dto/ServerInfo.java
  src/main/java/com/kuit/agarang/global/s3/utils/S3FileUtil.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/kuit/agarang/global/common/service/RedisServiceTest.java
Labels: 🌏 Deploy, 🔨 Refactor, ✨ Feature

#40 [Feature] 플레이리스트 조회 기능 구현
  src/main/java/com/kuit/agarang/domain/memory/model/dto/MemoryDTO.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/Memory.java
  src/main/java/com/kuit/agarang/domain/playlist/controller/PlaylistController.java
  src/main/java/com/kuit/agarang/domain/playlist/model/dto/MusicDto.java
  src/main/java/com/kuit/agarang/domain/playlist/model/dto/PlaylistDto.java
  src/main/java/com/kuit/agarang/domain/playlist/model/dto/PlaylistTracksResponse.java
  src/main/java/com/kuit/agarang/domain/playlist/model/dto/PlaylistsResponse.java
  src/main/java/com/kuit/agarang/domain/playlist/model/entity/MusicBookmark.java
  src/main/java/com/kuit/agarang/domain/playlist/repository/MemoryPlaylistRepository.java
  src/main/java/com/kuit/agarang/domain/playlist/repository/MusicBookmarkRepository.java
  src/main/java/com/kuit/agarang/domain/playlist/repository/PlaylistRepository.java
  src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
  src/main/resources/data.sql
Labels: 🔨 Refactor, 📬 API, ✨ Feature

#58 Feat : 추억 다이어리 즐겨찾기, 수정, 삭제 로직 추가
  src/main/java/com/kuit/agarang/domain/memory/controller/MemoryController.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/BookmarkRequest.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/DeleteMemoryRequest.java
  src/main/java/com/kuit/agarang/domain/memory/model/dto/ModifyMemoryRequest.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/Memory.java
  src/main/java/com/kuit/agarang/domain/memory/model/entity/MemoryBookmark.java
  src/main/java/com/kuit/agarang/domain/memory/repository/MemoryBookmarkRepository.java
  src/main/java/com/kuit/agarang/domain/memory/repository/MusicBookmarkRepository.java
  src/main/java/com/kuit/agarang/domain/memory/service/MemoryService.java
  src/main/java/com/kuit/agarang/domain/playlist/repository/MemoryPlaylistRepository.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponse.java
  src/main/java/com/kuit/agarang/global/common/model/dto/BaseResponseStatus.java
Labels: 📬 API, ✨ Feature

#62 [Fix] MusicBookmarkRepository 타입 오류 해결
  src/main/java/com/kuit/agarang/domain/memory/model/entity/MusicBookmark.java
  src/main/java/com/kuit/agarang/domain/memory/repository/MusicBookmarkRepository.java
  src/main/java/com/kuit/agarang/domain/playlist/repository/MusicBookmarkRepository.java
  src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
Labels: 🐞 BugFix

#64 Hotfix : Merge간 중복 클래스 생성 및 패키지 구조 변경으로 인한 오류 해결
  src/main/java/com/kuit/agarang/domain/memory/repository/MusicBookmarkRepository.java
  src/main/java/com/kuit/agarang/domain/memory/service/MemoryService.java
  src/main/java/com/kuit/agarang/domain/playlist/service/PlaylistService.java
Labels: 🐞 BugFix

#65 [Hotfix] redis-repository 및 jpa 빌드 설정
  src/main/java/com/kuit/agarang/global/common/config/RedisConfig.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#52 [Feature] Refresh Token 구현
  build.gradle
  src/main/java/com/kuit/agarang/domain/login/controller/ReissueController.java
  src/main/java/com/kuit/agarang/domain/login/enums/AuthProvider.java
  src/main/java/com/kuit/agarang/domain/login/filter/JWTFilter.java
  src/main/java/com/kuit/agarang/domain/login/handler/CustomSuccessHandler.java
  src/main/java/com/kuit/agarang/domain/login/handler/OAuth2SuccessHandler.java
  src/main/java/com/kuit/agarang/domain/login/model/dto/CustomOAuth2User.java
  src/main/java/com/kuit/agarang/domain/login/model/dto/GoogleResponse.java
  src/main/java/com/kuit/agarang/domain/login/model/dto/KakaoResponse.java
  src/main/java/com/kuit/agarang/domain/login/model/dto/NaverResponse.java
  src/main/java/com/kuit/agarang/domain/login/model/dto/OAuth2Response.java
  src/main/java/com/kuit/agarang/domain/login/model/dto/ReissueDto.java
  src/main/java/com/kuit/agarang/domain/login/model/entitiy/CustomOAuth2User.java
  src/main/java/com/kuit/agarang/domain/login/service/CustomOAuth2UserService.java
  src/main/java/com/kuit/agarang/domain/login/service/JWTService.java
  src/main/java/com/kuit/agarang/domain/login/service/LoginService.java
  src/main/java/com/kuit/agarang/domain/login/util/JwtProvider.java
  src/main/java/com/kuit/agarang/domain/login/utils/AuthenticationUtil.java
  src/main/java/com/kuit/agarang/domain/login/utils/CookieUtil.java
  src/main/java/com/kuit/agarang/domain/login/utils/JWTUtil.java
  src/main/java/com/kuit/agarang/domain/member/model/dto/MemberDTO.java
  src/main/java/com/kuit/agarang/domain/member/model/entity/Member.java
  src/main/java/com/kuit/agarang/domain/member/model/entity/RefreshToken.java
  src/main/java/com/kuit/agarang/domain/member/repository/MemberRepository.java
  src/main/java/com/kuit/agarang/domain/member/repository/RefreshRepository.java
  src/main/java/com/kuit/agarang/global/common/config/SecurityConfig.java
  src/main/java/com/kuit/agarang/global/common/exception/jwt/bad_request/JwtBadRequestException.java
  src/main/java/com/kuit/agarang/global/common/exception/jwt/bad_request/JwtNoTokenException.java
  src/main/java/com/kuit/agarang/global/common/exception/jwt/bad_request/JwtUnsupportedTokenException.java
  src/main/java/com/kuit/agarang/global/common/exception/jwt/unauthorized/JwtExpiredTokenException.java
  src/main/java/com/kuit/agarang/global/common/exception/jwt/unauthorized/JwtInvalidTokenException.java
  src/main/java/com/kuit/agarang/global/common/exception/jwt/unauthorized/JwtMalformedTokenException.java
  src/main/java/com/kuit/agarang/global/common/exception/jwt/unauthorized/JwtUnauthorizedTokenException.java
  src/main/java/com/kuit/agarang/global/common/response/BaseErrorResponse.java
  src/main/java/com/kuit/agarang/global/common/response/BaseResponse.java
  src/main/java/com/kuit/agarang/global/common/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/kuit/agarang/global/common/response/status/ResponseStatus.java
Labels: 🔨 Refactor, ✨ Feature
